# Site settings
title: VGuides
email: example@example.com
description: > # this means to ignore newlines until "baseurl:"
  Find useful guides for things / VGuides
baseurl: "/vguides-site" # the subpath of your site, e.g. /blog/
url: "http://hexagonwin.github.io" # the base hostname & protocol for your site
twitter_username: archvega
github_username:  archvega
